### ISSUE TITLE
Trailer header name

### ISSUE THREAD

**Issue by orlando-labs** [socketry/protocol-http1#14]
Hi, @ioquatix. 

Just confused by the usage of [trailer headers](https://tools.ietf.org/html/rfc7230#section-4.4). [RFC](https://tools.ietf.org/html/rfc7230) names it singular "Trailer" while the constant TRAILER [here](https://github.com/socketry/protocol-http1/blob/e8291e87fd7263f5b36e083cb6ff0fcd9c387fb3/lib/protocol/http1/body/chunked.rb#L29) and TRAILERS [here](https://github.com/socketry/protocol-http/blob/6af4239f683061787af3071c5814134b3931218d/lib/protocol/http/headers.rb#L40) are assigned with plural 'trailers'.

Shouldn't it be "trailer"?

**Comment by ioquatix** [comment]
Haha, this is great, it looks like I misread something somewhere. You do appear to be completely correct. Thanks for bringing the issue to my attention. It's kind of odd though because I did test this in Chrome at least it seemed to be working!? Maybe I was just seeing what I wanted.

This is an easy fix to I'll push it now.

**Comment by ioquatix** [comment]
Okay, this was fixed across all the gems. Released in async-http v0.56.0 and falcon v0.38.0.
