### ISSUE TITLE
I want to use spaces to indent a code

### ISSUE THREAD

**Issue by ganmacs** [socketry/protocol-http1#2]
Sorry if this issue is already discussed or duplicated one.

Ruby dev team no longer uses tabs[*](https://github.com/ruby/ruby/blob/70dcf5b368bfeee9bc054895fc046bf69d32aa91/.editorconfig) and ruby community uses space to indent code(e.g. [rails](https://github.com/rails/rails), [rubocop](https://github.com/rubocop-hq/rubocop) and [fluentd](https://github.com/fluent/fluentd) ). I think it doesn't matter whether using spaces or tab, but I believe it's good to follow the community standard since it will be easy to understand for new contributors.
I'm happy if `sockety` project uses spaces to indent code. Are there any reasons to use tabs to ident? 
@ioquatix

**Comment by ioquatix** [comment]
Yes, it's already discussed.

**Comment by ganmacs** [comment]
Could you please tell me the link of discussion? I'd like to know why this project uses spaces…

**Comment by ioquatix** [comment]
Let me summarise it so I can just link to it every time this discussion comes up.

**Comment by ioquatix** [comment]
This is my universal style guide, and I've linked through to RFC20 which explains the difference between tabs and spaces. https://github.com/ioquatix/universal-style-guide#indentation

If you've already invested in one way of doing indentation, its aways going to be a hard pill to swallow when someone does it differently. But look at it this way - diversity is good, even in code. Otherwise, we'd never make improvements.

**Comment by ganmacs** [comment]
Okay, I got your style. I'll follow this style in the project you organize (and I think that space or tab is a minor issue).
Thank you for your explanation. I'm glad to hear the reason 😄

**Comment by ioquatix** [comment]
https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/

**Comment by ganmacs** [comment]
thank you for interesting post.


BTW. can you review these reviews?
https://github.com/socketry/protocol-http1/pull/1
https://github.com/socketry/protocol-http2/pull/2
