### ISSUE TITLE
Potential breaking change in v0.10.1

### ISSUE THREAD

**Issue by bryanp** [socketry/protocol-http1#5]
v0.10.0 allowed non-string header values. But this change requires header values to be strings:

* https://github.com/socketry/protocol-http1/blob/master/lib/protocol/http1/connection.rb#L143

In my case, I'm setting `content-length` to an integer, which is failing on v0.10.1 but not v0.10.0. Does my code have to make sure all values are strings, or should it be guaranteed by this library?

**Comment by ioquatix** [comment]
What do you think is the right behaviour?

**Comment by ioquatix** [comment]
Also what does protocol-http2 do?

**Comment by bryanp** [comment]
On one hand it seems a bit odd that validation would occur as the response is written. `protocol-http` is low-level enough that maybe it should blindly write whatever it's given and let a higher level abstraction handle validation (`Protocol::HTTP::Response` or maybe even `async-http`).

But on the other hand you have more context in how this library is designed 😄 

Anyway, if you think this is the right place to validate the response, I think there are two options:

1. Typecast `value` to a string.

```ruby
def write_headers(headers)
  headers.each do |name, value|
    value = value.to_s

    raise BadResponse, "invalid value for header #{name}: #{value.inspect}" if value.match?(/\r|\n/)
    
    @stream.write("#{name}: #{value}\r\n")
  end
end
```

2. Validate that `value` is a string and doesn't include forbidden characters.

```ruby
def write_headers(headers)
  headers.each do |name, value|
    raise BadResponse, "invalid value for header #{name}: #{value.inspect}" if !value.is_a?(String) || value.match?(/\r|\n/)
    
    @stream.write("#{name}: #{value}\r\n")
  end
end
```

Picking 1 or 2 depends on whether you think this is the place for validation.

I'm not entirely sure what you're validating against, but another option might be to strip carriage returns and newlines instead of raising `BadResponse`. Can you provide more context here?

**Comment by ioquatix** [comment]
Only HTTP/1 has this issue. I’m not aware of any way to escape newlines in HTTP/1 headers.

The problem is it can break the response framing. This might be considered a security issue if the user can inject data that goes back out as a response header.

HTTP/2 is not affected. Because headers are encoded using HPACK.

Option 1 makes mores sense I guess.

**Comment by bryanp** [comment]
Is there an advantage to raising `BadResponse` over stripping newlines?

**Comment by ioquatix** [comment]
Well... I prefer explicit vs implicit, because it's actually an error in the user data. I think in theory we are only supposed to be shipping valid ASCII characters. Should we be validating that?

Obviously adding a lot of validation, is a big overhead. But maybe this validation is important. Better users know they are doing something wrong than it just implicitly gets set right... because it encourages a bad understanding of the system... they may wonder why data is not round tripping, etc.

**Comment by bryanp** [comment]
Okay, I like your thinking about explicit instead of implicit. Validating ASCII makes sense... AFAIK HTTP/1 headers are only supposed to contain ASCII characters.

**Comment by ioquatix** [comment]
From https://tools.ietf.org/html/rfc5234#appendix-B.1

```
VCHAR          =  %x21-7E
                                ; visible (printing) characters
```

From https://tools.ietf.org/html/rfc7230#section-3.2

```
   Each header field consists of a case-insensitive field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace.









Fielding & Reschke           Standards Track                   [Page 22]
 
RFC 7230           HTTP/1.1 Message Syntax and Routing         June 2014


     header-field   = field-name ":" OWS field-value OWS

     field-name     = token
     field-value    = *( field-content / obs-fold )
     field-content  = field-vchar [ 1*( SP / HTAB ) field-vchar ]
     field-vchar    = VCHAR / obs-text

     obs-fold       = CRLF 1*( SP / HTAB )
                    ; obsolete line folding
                    ; see Section 3.2.4
```

I wonder how much of this we should be validating.

Honestly, as long as it doesn't break framing (as \r\n characters can do), I don't really care the much.

**Comment by ioquatix** [comment]
I don't really understand what is `obs-text`, from https://tools.ietf.org/html/rfc7230#section-3.2.6

```
   A string of text is parsed as a single value if it is quoted using
   double-quote marks.

     quoted-string  = DQUOTE *( qdtext / quoted-pair ) DQUOTE
     qdtext         = HTAB / SP /%x21 / %x23-5B / %x5D-7E / obs-text
     obs-text       = %x80-FF
```

**Comment by bryanp** [comment]
So draw the line at security issues, essentially?

**Comment by ioquatix** [comment]
It would be nice to be able to draw a line somewhere.

In fact, the more I think about it, the less I'm sure what decision we should make.

So, certainly, there is an HTTP/1 specification and we should abide by that. But following it strictly hurts performance and in the optimal case (where users do the right thing) there is no benefit at all.

It's when users make mistakes that this kind of defensive programming makes sense. But we are essentially saying "here is the class of mistakes we will defend against" and "these other ones we don't care about". An example of this would be a header key with the value `"content-length: 5\r\ncontent-type"`. So, what you are asking me is, when do we decide if we should validate it or not, and my decision here probably seems super arbitrary, which in a way I suppose it is.

I don't really feel that this is a security issue. In order for this issue to be exploited, a user would have to knowingly inject untrusted data into a header value.

The reason why I felt motivated to add this check, is because it fundamentally breaks the HTTP framing. But actually, there are other ways to do that as demonstrated above. So, why this one?

Honestly, what would make more sense to me is a debug layer that you can choose to sit between the protocol layer and the upper layer that has the mandate to implement any and all validations. This is used during tests but optionally during production.

So, I'd be willing to revert this, but with the proviso that we actually do something better.

**Comment by bryanp** [comment]
You make some really good points here. This really is the crux of the issue:

> The reason why I felt motivated to add this check, is because it fundamentally breaks the HTTP framing. But actually, there are other ways to do that as demonstrated above. So, why this one?

I honestly think we can draw the line at any arbitrary point as long as it's explained somewhere and consistently followed. It also seems users only hit these kinds of issues if 1) they don't know what they are doing or 2) they are dealing with untrusted values. 

To me, solving the first issue feels out of scope for this library.

Solving the second issue though seems completely reasonable. Performing validation at response time is unfortunate, since in most cases it won't be necessary and it hurts performance if we are consistent and validate the entire spec. Ignoring issues encountered by users who don't know what they are doing, validation really only helps when dealing with untrusted values.

What it we provide a set of helpers that allow the user to secure values they know to be untrusted? Maybe get the helpers through the request, so we know what http spec to enforce.

```ruby
headers = Protocol::HTTP::Headers.new
headers.add(key, request.security.secure_header_value(...))
Protocol::HTTP::Response.new(..., headers, ...)
```

Maybe security helpers would raise `Protocol::HTTP::Insecure` when an issue is encountered.

Does this make sense? In summary:

* State that the library will write whatever values provided because it prioritizes performance over being secure by default. 
* List the places a user should be concerned when dealing with untrusted input, along with applicable helpers. 
* Let higher level libraries provide security by default. For example in my use case I'd use the `secure_header_value` helper in the framework anytime a header value was set by the user.

**Comment by ioquatix** [comment]
This makes sense. Because `Protocol::HTTP::Headers` is already high level, maybe we can add validations. It's also better to fail at the point where the user calls `#add` rather than somewhere deep in the guts of the protocol code.

**Comment by ioquatix** [comment]
It would be interesting to see if `setHeader` does validation:

https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/#setting-response-headers

**Comment by bryanp** [comment]
It appears to:

```
_http_outgoing.js:529
    throw new ERR_INVALID_CHAR('header content', name);
    ^

TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Type"]
    at ServerResponse.setHeader (_http_outgoing.js:538:3)
    at Server.<anonymous> (/Users/bryanp/Downloads/server.js:8:7)
    at Server.emit (events.js:321:20)
    at parserOnIncoming (_http_server.js:780:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17) {
  code: 'ERR_INVALID_CHAR'
}
```

Here's the code I used:

```js
const http = require('http')

const hostname = 'localhost'
const port = 3000

const server = http.createServer((req, res) => {
  res.statusCode = 200
  res.setHeader('Content-Type', "text/plain\r\nfoo/bar")
  res.end('hello\n')
})

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`)
})
```

Validating in `Protocol::HTTP::Headers#add` feels right to me. I'll knock out this refactor in the next couple days.

**Comment by ioquatix** [comment]
Currently, all headers are converted to strings.

https://github.com/socketry/protocol-http1/blob/master/lib/protocol/http1/connection.rb#L152-L156

This is probably the right behaviour, but I'm planning to review this behaviour before a final 1.0 release.
